version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |   #3rdline, just add a name it doesn't matter, 4th line, you need bucketname from the bucket file
          aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name stackit-${CIRCLE_WORKFLOW_ID} \
            --parameter-overrides entername="${CIRCLE_WORKFLOW_ID}"     
      - run: aws s3 sync . s3://stackit-${CIRCLE_WORKFLOW_ID} --delete

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"


workflows:
    schemas:
      jobs:
        - create_and_deploy_front_end
        - promote_to_production:
            requires: 
              - create_and_deploy_front_end