Description: >
    Create EC2 - SecGroup

Resources:
    Instance:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: ami-005bdb005fb00e791
            KeyName: BastionKey   #Make the key as a var for rotation
            InstanceType: t2.micro #No need for var, bastion shouldn't be dynamic
            SecurityGroupIds:
            - !Ref ECsecgroup
    ECsecgroup:    #Create the Sec GROUP for the BASTION
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: Allow SSH from public
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0

